import { randomUUID } from "node:crypto";
import type { ActorRef } from "../contracts/actors.ts";
import type { FrameworkConfiguration } from "../contracts/configuration.ts";
import { authorizeExecution, grantApproval, requestApproval, validateApproval, verifyExecutiveApprovalReceipt, waiveApproval, type ApprovalVerification, type ApprovalRecord, type DecisionRecord, type SignedExecutiveApprovalReceipt } from "../approvals/index.ts";
import { assessMateriality } from "../policy/materiality.ts";
import { buildTaskPacket } from "../workflows/task-packets.ts";
import type { WorkspaceSnapshot } from "../evidence/index.ts";
import { assertTransition, actionTransitions, approvalTransitions, assignmentTransitions, executionTransitions, planTransitions, taskTransitions } from "../workflows/transitions.ts";
import type { ActionState, AdapterOperations, AssignmentAggregate, CommandContext, CommandResponse, ExecutionPacketInput, ExecutionState, HandoverRequest, PauseRequest, PlanState, ResultState, SteerRequest, TaskState, WorkflowEvent, WorkflowRepository } from "./types.ts";

const uid = (p: string) => `${p}-${randomUUID()}`;
const now = (c: CommandContext) => c.now?.() ?? new Date();
const copy = <T>(v: T): T => structuredClone(v);

export class WorkflowCommandService {
  private readonly repo: WorkflowRepository;
  private readonly config: FrameworkConfiguration;
  private readonly adapter: AdapterOperations;
  constructor(repo: WorkflowRepository, config: FrameworkConfiguration, adapter: AdapterOperations) { this.repo = repo; this.config = config; this.adapter = adapter; }
  private evt(type: string, a: AssignmentAggregate, c: CommandContext, data: Record<string, unknown> = {}): WorkflowEvent { return { type, assignmentId: a.assignmentId, actor: c.actor, data, at: now(c).toISOString() }; }
  private async owner(a: AssignmentAggregate, c: CommandContext) { if (a.managerInstanceId !== c.managerInstanceId) throw new Error("OWNERSHIP_REQUIRED: manager does not own assignment"); const lease = await this.repo.validateOwnership?.(a.assignmentId, c.managerInstanceId, c.ownershipToken, now(c)); if (this.repo.validateOwnership && !lease) throw new Error("OWNERSHIP_REQUIRED: valid renewable ownership lease required"); if (lease) a.ownershipLease = lease; }
  private async mutate<T>(assignmentId: string, c: CommandContext, fn: (a: AssignmentAggregate, emit: (t: string, d?: Record<string, unknown>) => void) => T | Promise<T>): Promise<T> { return this.repo.transaction(assignmentId, async tx => { const found = await tx.get(); if (!found) throw new Error(`Assignment not found: ${assignmentId}`); const a = copy(found); await this.owner(a, c); const events: WorkflowEvent[] = []; const result = await fn(a, (t, d = {}) => events.push(this.evt(t, a, c, d))); await tx.save(a); for (const e of events) await tx.append(e); return result; }); }
  private required(k: "initial" | "resume" | "material") { return (k === "initial" ? this.config.approvals.initialPlan : k === "resume" ? this.config.approvals.resumePlan : this.config.approvals.materialPlanChange) === "required"; }
  private authenticateApproval(a: AssignmentAggregate, approval: ApprovalRecord, decision: "approve" | "reject" | "waive", assertedActor: ActorRef, c: CommandContext, receipt?: SignedExecutiveApprovalReceipt): { actor: ActorRef; verification: ApprovalVerification } {
    const policy = this.config.security.executiveApproval;
    if (policy.mode === "record_only") return { actor: assertedActor, verification: { mode: "record_only" } };
    if (!receipt) throw new Error("APPROVAL_RECEIPT_REQUIRED: signed executive approval receipt is required");
    return verifyExecutiveApprovalReceipt({ receipt, trustedPublicKeys: policy.trustedPublicKeys, receiptMaxAgeSeconds: policy.receiptMaxAgeSeconds, now: now(c), expected: { approvalId: approval.approvalId, assignmentId: a.assignmentId, planId: approval.subjectId, planRevision: approval.subjectRevision, scope: approval.scope, decision } });
  }

  async start(input: { objective: string; approach: string[]; acceptanceCriteria: string[]; waiveApproval?: boolean }, c: CommandContext): Promise<CommandResponse> {
    if (!input.objective.trim()) throw new Error("Objective is required"); if (input.waiveApproval && c.actor.actorType !== "executive") throw new Error("Only an executive may waive initial approval");
    const assignmentId = uid("asn"), planId = uid("pln"), at = now(c), needs = this.required("initial") && !input.waiveApproval;
    const plan: PlanState = { planId, revision: 1, purpose: "initial", lifecycle: needs ? "proposed" : "active", approach: [...input.approach], acceptanceCriteria: [...input.acceptanceCriteria] };
    const req = requestApproval({ approvalId: uid("apr"), subjectType: "plan", subjectId: planId, subjectRevision: 1, scope: "execute", approver: c.actor }, at);
    const approval = needs ? req : input.waiveApproval ? waiveApproval(req, c.actor) : { ...req, state: "waived" as const, waiverAuthority: { actorId: "runtime-policy", actorType: "runtime" as const } };
    const authority = needs ? { assignmentId, planId, planRevision: 1, state: "unauthorized" as const, reason: "approval_required", updatedAt: at.toISOString() } : authorizeExecution(assignmentId, planId, 1, approval, at);
    const lease = await this.repo.acquireOwnership?.(assignmentId, c.managerInstanceId, at);
    const a: AssignmentAggregate = { assignmentId, objective: input.objective, lifecycle: needs ? "awaiting_approval" : "running", executionAuthority: authority, currentPlan: plan, plans: [plan], approvals: [approval], tasks: [], executions: [], results: [], actions: [], assessments: [], decisions: [], pendingActionIds: [], closureHistory: [], managerInstanceId: c.managerInstanceId, ...(lease ? { ownershipLease: lease } : {}), checkpoints: [], taskPackets: [], nonmaterialChangeCount: 0, holds: [] };
    await this.repo.transaction(assignmentId, async tx => { if (await tx.get()) throw new Error("Assignment already exists"); await tx.save(a); for (const e of [this.evt("assignment.created", a, c, { planId }), this.evt("plan.proposed", a, c, { planId, revision: 1 }), this.evt("approval.requested", a, c, { approvalId: req.approvalId, planId, revision: 1 }), ...(needs ? [] : [this.evt("plan.approval_waived", a, c, { approvalId: approval.approvalId }), this.evt("assignment.execution_authorized", a, c, { approvalId: approval.approvalId })])]) await tx.append(e); });
    return { status: needs ? "blocked" : "succeeded", code: needs ? "APPROVAL_REQUIRED" : "EXECUTION_AUTHORIZED", assignment: copy(a) };
  }
  async resume(input: { assignmentId: string; waiveApproval?: boolean }, c: CommandContext): Promise<CommandResponse> { return this.mutate(input.assignmentId, c, (a, emit) => { if (input.waiveApproval && c.actor.actorType !== "executive") throw new Error("Only an executive may waive resume approval"); if (!["paused", "handover_ready", "blocked"].includes(a.lifecycle)) throw new Error(`Assignment in ${a.lifecycle} cannot resume`); const checkpoint = { checkpointId: uid("chk"), kind: "resume" as const, summary: `Resume ${a.currentPlan.planId} revision ${a.currentPlan.revision}`, createdAt: now(c).toISOString(), unresolvedActionIds: [...a.pendingActionIds] }; a.checkpoints = [...(a.checkpoints ?? []), checkpoint]; const needs = this.required("resume") && !input.waiveApproval, req = requestApproval({ approvalId: uid("apr"), subjectType: "plan", subjectId: a.currentPlan.planId, subjectRevision: a.currentPlan.revision, scope: "resume", approver: c.actor }, now(c)); const approval = needs ? req : input.waiveApproval ? waiveApproval(req, c.actor) : { ...req, state: "waived" as const, waiverAuthority: { actorId: "runtime-policy", actorType: "runtime" as const } }; a.approvals.push(approval); a.lifecycle = needs ? "awaiting_approval" : "running"; a.executionAuthority = { assignmentId: a.assignmentId, planId: a.currentPlan.planId, planRevision: a.currentPlan.revision, state: needs ? "unauthorized" : "authorized", approvalId: approval.approvalId, reason: needs ? "resume_approval_required" : "waived", updatedAt: now(c).toISOString() }; emit("assignment.resume_requested", { checkpointId: checkpoint.checkpointId, approvalId: approval.approvalId }); emit("assignment.context_restored", { checkpointId: checkpoint.checkpointId, planId: a.currentPlan.planId, revision: a.currentPlan.revision }); emit("approval.requested", { approvalId: req.approvalId, planId: a.currentPlan.planId, revision: a.currentPlan.revision }); return { status: needs ? "blocked" : "succeeded", code: needs ? "APPROVAL_REQUIRED" : "EXECUTION_AUTHORIZED", assignment: copy(a) }; }); }
  async status(id: string, c: CommandContext): Promise<CommandResponse> { const a=await this.repo.get(id);if(!a)throw new Error(`Assignment not found: ${id}`);await this.repo.append(this.evt("manager.status_reported",a,c));return { status: "succeeded", code: "READ_ONLY", assignment: copy(a) }; }
  async ask(id: string, question: string, c: CommandContext): Promise<CommandResponse<{question: string}>> { const a=await this.repo.get(id);if(!a)throw new Error(`Assignment not found: ${id}`);await this.repo.append(this.evt("manager.question_received",a,c,{question}));return { status: "succeeded", code: "READ_ONLY", assignment: copy(a), data: { question } }; }
  async approvePlan(id: string, approvalId: string, actor: ActorRef, c: CommandContext, receipt?: SignedExecutiveApprovalReceipt): Promise<CommandResponse> { return this.mutate(id, c, (a, e) => { const i = a.approvals.findIndex(x => x.approvalId === approvalId); if (i < 0) throw new Error("Approval not found"); const auth=this.authenticateApproval(a,a.approvals[i]!,"approve",actor,c,receipt),granted = { ...grantApproval(a.approvals[i]!, auth.actor, now(c)), verification:auth.verification }, scope = granted.scope === "resume" ? "resume" : "execute", d = validateApproval(granted, { type: "plan", id: a.currentPlan.planId, revision: a.currentPlan.revision, scope }, now(c)); if (!d.allowed) throw new Error(`${d.code}: ${d.reason}`); a.approvals[i] = granted; a.executionAuthority = scope === "execute" ? authorizeExecution(id, a.currentPlan.planId, a.currentPlan.revision, granted, now(c)) : { assignmentId: id, planId: a.currentPlan.planId, planRevision: a.currentPlan.revision, state: "authorized", approvalId, reason: "granted", updatedAt: now(c).toISOString() }; a.currentPlan.lifecycle = "active"; a.lifecycle = "running"; a.holds = []; e("approval.granted", { approvalId, verificationMode: auth.verification.mode }); e("plan.approved", { approvalId }); e("assignment.execution_authorized", { approvalId }); return { status: "succeeded", code: "EXECUTION_AUTHORIZED", assignment: copy(a) }; }); }
  async rejectPlan(id: string, approvalId: string, actor: ActorRef, reason: string, c: CommandContext, receipt?: SignedExecutiveApprovalReceipt): Promise<CommandResponse> { return this.mutate(id, c, (a,e) => { const p = a.approvals.find(x => x.approvalId === approvalId); if (!p) throw new Error("Approval not found");const auth=this.authenticateApproval(a,p,"reject",actor,c,receipt);if(auth.actor.actorType!=="executive")throw new Error("Only an executive may reject plan approval"); assertTransition(approvalTransitions,p.state,"rejected","approval"); p.state="rejected";p.approver=auth.actor;p.verification=auth.verification;a.lifecycle="blocked";a.executionAuthority={...a.executionAuthority,state:"unauthorized",reason,updatedAt:now(c).toISOString()}; e("approval.rejected",{approvalId,verificationMode:auth.verification.mode}); e("plan.rejected",{approvalId,reason}); return {status:"blocked",code:"PLAN_REJECTED",assignment:copy(a)}; }); }
  async waivePlanApproval(id:string,approvalId:string,actor:ActorRef,c:CommandContext,receipt?:SignedExecutiveApprovalReceipt):Promise<CommandResponse>{return this.mutate(id,c,(a,e)=>{const i=a.approvals.findIndex(x=>x.approvalId===approvalId);if(i<0)throw new Error("Approval not found");const auth=this.authenticateApproval(a,a.approvals[i]!,"waive",actor,c,receipt),w={...waiveApproval(a.approvals[i]!,auth.actor),verification:auth.verification};a.approvals[i]=w;a.executionAuthority={assignmentId:id,planId:w.subjectId,planRevision:w.subjectRevision,state:"authorized",approvalId,reason:"waived",updatedAt:now(c).toISOString()};a.currentPlan.lifecycle="active";a.lifecycle="running";a.holds=[];e("plan.approval_waived",{approvalId,verificationMode:auth.verification.mode});e("assignment.execution_authorized",{approvalId});return{status:"succeeded",code:"EXECUTION_AUTHORIZED",assignment:copy(a)};});}
  async steer(input:SteerRequest,c:CommandContext):Promise<CommandResponse>{return this.mutate(input.assignmentId,c,(a,e)=>{if(a.lifecycle==="awaiting_approval"||a.executionAuthority.state==="held")throw new Error("PLAN_APPROVAL_PENDING: resolve the current plan approval before steering");e("assignment.steer_requested",{paths:input.paths});const m=assessMateriality({paths:input.paths,rationale:input.rationale,priorNonmaterialChangeCount:a.nonmaterialChangeCount},this.config.materiality),needs=!m.allowed&&this.required("material"),prior=a.currentPlan,plan:PlanState={planId:uid("pln"),revision:prior.revision+1,purpose:"steer",lifecycle:needs?"proposed":"active",approach:[...input.approach],acceptanceCriteria:[...input.acceptanceCriteria],priorPlanId:prior.planId};e("plan.change_assessed",{classification:m.classification,code:m.code});assertTransition(planTransitions,prior.lifecycle,"superseded","plan");prior.lifecycle="superseded";a.plans.push(plan);a.currentPlan=plan;a.assessments.push({...m,assessmentId:uid("asm"),createdAt:now(c).toISOString(),planId:plan.planId,planRevision:plan.revision});if(needs){a.holds=[...new Set([...a.holds,...input.paths])];a.lifecycle="awaiting_approval";a.executionAuthority={assignmentId:a.assignmentId,planId:plan.planId,planRevision:plan.revision,state:"held",reason:m.code,updatedAt:now(c).toISOString()};const p=requestApproval({approvalId:uid("apr"),subjectType:"plan",subjectId:plan.planId,subjectRevision:plan.revision,scope:"execute",approver:c.actor},now(c));a.approvals.push(p);e("approval.requested",{approvalId:p.approvalId,planId:plan.planId,revision:plan.revision});}else a.nonmaterialChangeCount=m.cumulativeCount;e("plan.superseded",{planId:prior.planId});e("plan.proposed",{planId:plan.planId,revision:plan.revision});return{status:needs?"blocked":"succeeded",code:needs?m.code:"NONMATERIAL_CHANGE",assignment:copy(a)};});}
  async pause(input:PauseRequest,c:CommandContext):Promise<CommandResponse>{return this.mutate(input.assignmentId,c,async(a,e)=>{const mode=input.mode??this.config.execution.defaultInterruptionMode;assertTransition(assignmentTransitions,a.lifecycle,"pausing","assignment");a.lifecycle="pausing";e("assignment.pause_requested",{mode});let incomplete=false;for(const x of a.executions.filter(x=>x.state==="running")){e("execution.stop_requested",{executionId:x.executionId,taskId:x.taskId,mode});const o=await this.adapter.requestStop({assignmentId:a.assignmentId,executionId:x.executionId,mode,...(input.timeoutMs===undefined?{}:{timeoutMs:input.timeoutMs})});if(o.confirmed){x.state="cancelled";if(o.checkpointId){a.checkpoints=[...(a.checkpoints??[]),{checkpointId:o.checkpointId,kind:"pause",summary:`Execution ${x.executionId} checkpointed`,createdAt:now(c).toISOString(),unresolvedActionIds:[]}];e("execution.checkpointed",{executionId:x.executionId,taskId:x.taskId,checkpointId:o.checkpointId});}e("execution.stopped",{executionId:x.executionId,taskId:x.taskId});e("execution.cancelled",{executionId:x.executionId,taskId:x.taskId});}else{x.state="unknown";incomplete=true;e("execution.outcome_unknown",{executionId:x.executionId,taskId:x.taskId});}}a.lifecycle=incomplete?"blocked":"paused";a.executionAuthority={...a.executionAuthority,state:"held",reason:incomplete?"pause_incomplete":"paused",updatedAt:now(c).toISOString()};e(incomplete?"assignment.pause_incomplete":"assignment.paused",{mode});return{status:incomplete?"blocked":"succeeded",code:incomplete?"PAUSE_INCOMPLETE":"PAUSED",assignment:copy(a)};});}
  async handover(input:HandoverRequest,c:CommandContext):Promise<CommandResponse<{packageId?:string}>>{const current=await this.repo.get(input.assignmentId);if(!current)throw new Error(`Assignment not found: ${input.assignmentId}`);if(!["paused","blocked","handover_ready"].includes(current.lifecycle))await this.pause(input,c);return this.mutate(input.assignmentId,c,async(a,e)=>{a.lifecycle="handing_over";e("assignment.handover_requested",{mode:input.mode??this.config.execution.defaultInterruptionMode,receiverManagerInstanceId:input.receiverManagerInstanceId});const p=await this.adapter.createTransferPackage({assignment:copy(a),receiverManagerInstanceId:input.receiverManagerInstanceId}),createdAt=now(c).toISOString();if(!(a.checkpoints??[]).some(checkpoint=>checkpoint.checkpointId===p.packageId))a.checkpoints=[...(a.checkpoints??[]),{checkpointId:p.packageId,kind:"handover",summary:`Handover package for ${input.receiverManagerInstanceId}`,createdAt,unresolvedActionIds:[...a.pendingActionIds]}];if(!p.valid||a.executions.some(x=>x.state==="unknown")){a.lifecycle="blocked";a.handover={packageId:p.packageId,receiverManagerInstanceId:input.receiverManagerInstanceId,status:"incomplete",createdAt};e("assignment.handover_incomplete",{packageId:p.packageId});return{status:"blocked",code:"HANDOVER_INCOMPLETE",assignment:copy(a),data:{packageId:p.packageId}};}a.lifecycle="handover_ready";a.handover={packageId:p.packageId,receiverManagerInstanceId:input.receiverManagerInstanceId,status:"ready",createdAt};e("assignment.handover_ready",{packageId:p.packageId});const accepted=await this.adapter.transferOwnership({assignmentId:a.assignmentId,fromManagerInstanceId:a.managerInstanceId,receiverManagerInstanceId:input.receiverManagerInstanceId,packageId:p.packageId});if(!accepted.accepted)return{status:"blocked",code:"OWNERSHIP_ACCEPTANCE_REQUIRED",assignment:copy(a),data:{packageId:p.packageId}};const oldManager=a.managerInstanceId,token=a.ownershipLease?.token??c.ownershipToken;if(this.repo.transferOwnership){if(!token)throw new Error("OWNERSHIP_REQUIRED: lease token required for handover");a.ownershipLease=await this.repo.transferOwnership(a.assignmentId,oldManager,input.receiverManagerInstanceId,token,now(c));}e("manager.ownership_released",{managerInstanceId:oldManager,packageId:p.packageId});a.managerInstanceId=input.receiverManagerInstanceId;a.handover.status="accepted";e("manager.ownership_acquired",{managerInstanceId:input.receiverManagerInstanceId,packageId:p.packageId});return{status:"succeeded",code:"HANDOVER_ACCEPTED",assignment:copy(a),data:{packageId:p.packageId}};});}
  async createTask(id:string,paths:string[],c:CommandContext):Promise<TaskState>{return this.mutate(id,c,(a,e)=>{const t:TaskState={taskId:uid("tsk"),state:"draft",affectedPaths:paths,executionIds:[],resultIds:[]};a.tasks.push(t);e("task.created",{taskId:t.taskId});return copy(t);});}
  async transitionTask(id:string,taskId:string,next:TaskState["state"],c:CommandContext):Promise<TaskState>{return this.mutate(id,c,(a,e)=>{const t=a.tasks.find(x=>x.taskId===taskId);if(!t)throw new Error("Task not found");if(next==="dispatched"&&(a.executionAuthority.state!=="authorized"||t.affectedPaths.some(p=>a.holds.includes(p))))throw new Error("AFFECTED_WORK_HELD: task cannot dispatch");assertTransition(taskTransitions,t.state,next,"task");const prior=t.state;t.state=next;if(next==="ready")e("task.validated",{taskId});if(next==="dispatched"){e("task.dispatch_requested",{taskId});e("task.dispatched",{taskId});}if(next==="rework"){e("result.changes_requested",{taskId});e("task.change_requested",{taskId,priorState:prior});}if(next==="accepted")e("result.accepted",{taskId});if(next==="closed")e("task.closed",{taskId});return copy(t);});}
  async beginExecution(id:string,taskId:string,c:CommandContext,packet?:ExecutionPacketInput,workspaceSnapshot?:WorkspaceSnapshot):Promise<ExecutionState>{return this.mutate(id,c,(a,e)=>{const t=a.tasks.find(x=>x.taskId===taskId);if(!t)throw new Error("Task not found");if(a.executionAuthority.state!=="authorized"||t.affectedPaths.some(p=>a.holds.includes(p)))throw new Error("EXECUTION_AUTHORITY_MISSING");if(t.state==="rework"){t.state="ready";e("task.validated",{taskId,rework:true});}if(t.state==="ready"){e("task.dispatch_requested",{taskId});t.state="dispatched";e("task.dispatched",{taskId});}assertTransition(taskTransitions,t.state,"running","task");const x:ExecutionState={executionId:uid("exe"),taskId,attempt:t.executionIds.length+1,state:"running"};if(packet){const role=packet.purpose??"";if(!this.config.roles.enabled.includes(role))throw new Error("ROLE_NOT_ALLOWED: task role must be enabled as purpose");const requested=`${packet.requested_model.provider}:${packet.requested_model.model}`,allowed=this.config.models.roles[role]?.allowed??[];if(allowed.length&&!allowed.includes(requested))throw new Error("MODEL_NOT_ALLOWED");if(this.config.providers[packet.requested_model.provider]?.enabled===false)throw new Error("PROVIDER_CAPABILITY_UNAVAILABLE");a.taskPackets=[...(a.taskPackets??[]),buildTaskPacket({...packet,task_id:taskId,execution_id:x.executionId,assignment_id:id},now(c))];}t.state="running";t.executionIds.push(x.executionId);a.executions.push(x);if(workspaceSnapshot){const evidenceId=uid("evd");a.evidence=[...(a.evidence??[]),{evidenceId,subjectType:"execution",subjectId:x.executionId,kind:"git-working-tree-before",location:workspaceSnapshot.location,digest:workspaceSnapshot.digest,createdAt:workspaceSnapshot.capturedAt}];e("evidence.recorded",{evidenceId,executionId:x.executionId});}e("execution.started",{taskId,executionId:x.executionId,attempt:x.attempt});return copy(x);});}
  async beginManagedExecution(id:string,taskId:string,role:string,packet:ExecutionPacketInput,c:CommandContext,workspaceSnapshot?:WorkspaceSnapshot):Promise<ExecutionState>{if(!role.trim())throw new Error("ROLE_NOT_ALLOWED: role is required");return this.beginExecution(id,taskId,c,{...packet,purpose:role},workspaceSnapshot);}
  async recordExecutionOutcome(id:string,executionId:string,outcome:"completed"|"failed"|"cancelled"|"unknown",c:CommandContext,workspaceSnapshot?:WorkspaceSnapshot):Promise<ExecutionState>{return this.mutate(id,c,(a,e)=>{const x=a.executions.find(x=>x.executionId===executionId);if(!x)throw new Error("Execution not found");assertTransition(executionTransitions,x.state,outcome,"execution");x.state=outcome;if(workspaceSnapshot){const before=(a.evidence??[]).find(item=>item.subjectId===executionId&&item.kind==="git-working-tree-before");const evidenceId=uid("evd"),unchanged=before?.digest===workspaceSnapshot.digest;a.evidence=[...(a.evidence??[]),{evidenceId,subjectType:"execution",subjectId:executionId,kind:`git-working-tree-after:${unchanged?"unchanged":"changed"}`,location:workspaceSnapshot.location,digest:workspaceSnapshot.digest,createdAt:workspaceSnapshot.capturedAt}];e("evidence.recorded",{evidenceId,executionId,unchanged});}e(`execution.${outcome==="unknown"?"outcome_unknown":outcome}`,{executionId,taskId:x.taskId});return copy(x);});}
  async submitResult(id:string,taskId:string,resultId:string,c:CommandContext,details?:{executionId:string;deliveryStatus:ResultState["deliveryStatus"];summary:string}):Promise<TaskState>{return this.mutate(id,c,(a,e)=>{const t=a.tasks.find(x=>x.taskId===taskId);if(!t)throw new Error("Task not found");assertTransition(taskTransitions,t.state,"result_submitted","task");t.state="result_submitted";t.resultIds.push(resultId);if(details){const evidenceIds=(a.evidence??[]).filter(item=>item.subjectType==="execution"&&item.subjectId===details.executionId).map(item=>item.evidenceId);a.results.push({resultId,taskId,...details,...(evidenceIds.length?{evidenceIds}:{})});}e("submission.received",{taskId,resultId,...(details?{executionId:details.executionId}:{})});return copy(t);});}
  async requestRework(a:string,t:string,c:CommandContext){return this.transitionTask(a,t,"rework",c);} async acceptResult(a:string,t:string,c:CommandContext){return this.transitionTask(a,t,"accepted",c);} async closeTask(a:string,t:string,c:CommandContext){return this.transitionTask(a,t,"closed",c);}
  async createAction(id:string,description:string,c:CommandContext,refs:{taskId?:string;executionId?:string}={}):Promise<ActionState>{return this.mutate(id,c,(a,e)=>{const x:ActionState={actionId:uid("act"),description,state:"requested",...refs};a.actions.push(x);e("action.intent_recorded",{actionId:x.actionId,description});return copy(x);});}
  async recordActionOutcome(id:string,actionId:string,outcome:"started"|"succeeded"|"failed"|"prevented"|"cancelled"|"unknown",c:CommandContext):Promise<ActionState>{return this.mutate(id,c,(a,e)=>{const x=a.actions.find(x=>x.actionId===actionId);if(!x)throw new Error("Action not found");assertTransition(actionTransitions,x.state,outcome,"action");x.state=outcome;if(outcome==="unknown")a.pendingActionIds=[...new Set([...a.pendingActionIds,actionId])];e(`action.${outcome==="unknown"?"outcome_unknown":outcome}`,{actionId});return copy(x);});}
  async reconcileAction(id:string,actionId:string,outcome:"succeeded"|"failed"|"prevented"|"cancelled",c:CommandContext):Promise<ActionState>{return this.mutate(id,c,(a,e)=>{const x=a.actions.find(x=>x.actionId===actionId);if(!x||x.state!=="unknown"||!a.pendingActionIds.includes(actionId))throw new Error("Action does not have a pending unknown outcome");assertTransition(actionTransitions,x.state,outcome,"action");x.state=outcome;a.pendingActionIds=a.pendingActionIds.filter(x=>x!==actionId);e("action.reconciled",{actionId,outcome});return copy(x);});}
  async recordDecision(id:string,choice:string,rationale:string,c:CommandContext):Promise<DecisionRecord>{return this.mutate(id,c,(a,e)=>{const d={decisionId:uid("dec"),subjectId:id,choice,rationale,decidedBy:c.actor,decidedAt:now(c).toISOString()};a.decisions.push(d);e("decision.recorded",{decisionId:d.decisionId});return copy(d);});}
  async cancelAssignment(id:string,c:CommandContext):Promise<CommandResponse>{return this.mutate(id,c,(a,e)=>{assertTransition(assignmentTransitions,a.lifecycle,"cancelling","assignment");a.lifecycle="cancelling";if(a.executions.some(x=>x.state==="running"||x.state==="unknown")||a.pendingActionIds.length){a.lifecycle="blocked";e("assignment.execution_blocked",{reason:"active_or_unknown_execution"});return{status:"blocked",code:"UNKNOWN_OUTCOME_UNRESOLVED",assignment:copy(a)};}for(const task of a.tasks){if(task.state!=="closed"&&task.state!=="cancelled"){assertTransition(taskTransitions,task.state,"cancelled","task");task.state="cancelled";e("task.cancelled",{taskId:task.taskId});}}return this.close(a,"cancelled",c,e);});}
  async closeAssignment(id:string,c:CommandContext):Promise<CommandResponse>{return this.mutate(id,c,(a,e)=>{if(a.lifecycle!=="running")throw new Error(`Assignment in ${a.lifecycle} cannot complete`);if(a.executions.some(x=>x.state==="running"||x.state==="unknown")||a.pendingActionIds.length)return{status:"blocked",code:"UNKNOWN_OUTCOME_UNRESOLVED",assignment:copy(a)};if(a.tasks.some(x=>x.state!=="closed"))return{status:"blocked",code:"INCOMPLETE_TASKS",assignment:copy(a)};return this.close(a,"completed",c,e);});}
  private close(a:AssignmentAggregate,d:"completed"|"cancelled",c:CommandContext,e:(t:string,d?:Record<string,unknown>)=>void):CommandResponse{a.lifecycle="closed";a.executionAuthority={...a.executionAuthority,state:"unauthorized",reason:d,updatedAt:now(c).toISOString()};a.closureHistory.push({disposition:d,closedAt:now(c).toISOString()});e("assignment.closed",{disposition:d});return{status:"succeeded",code:"ASSIGNMENT_CLOSED",assignment:copy(a)};}
  async reopenAssignment(id:string,c:CommandContext):Promise<CommandResponse>{await this.mutate(id,c,a=>{assertTransition(assignmentTransitions,a.lifecycle,"awaiting_approval","assignment");a.lifecycle="paused";});return this.resume({assignmentId:id},c);}
  async renewOwnership(id:string,c:CommandContext):Promise<string>{if(!c.ownershipToken||!this.repo.renewOwnership)throw new Error("OWNERSHIP_REQUIRED: ownership token and renewable repository required");const lease=await this.repo.renewOwnership(id,c.managerInstanceId,c.ownershipToken,now(c));await this.mutate(id,{...c,ownershipToken:lease.token},a=>{a.ownershipLease=lease;});return lease.token;}
  async acquireOwnership(id: string, c: CommandContext): Promise<CommandResponse> {
    if (!this.repo.acquireOwnership) throw new Error("OWNERSHIP_UNSUPPORTED: repository cannot acquire an ownership lease");
    const existing = await this.repo.get(id);
    if (!existing) throw new Error(`Assignment not found: ${id}`);
    if (existing.managerInstanceId !== c.managerInstanceId) throw new Error("OWNERSHIP_REQUIRED: only the recorded manager may reacquire an expired lease; use handover for a different manager");
    const lease = await this.repo.acquireOwnership(id, c.managerInstanceId, now(c));
    return this.repo.transaction(id, async tx => {
      const found = await tx.get();
      if (!found) throw new Error(`Assignment not found: ${id}`);
      if (found.managerInstanceId !== c.managerInstanceId) throw new Error("OWNERSHIP_REQUIRED: assignment owner changed while acquiring lease");
      found.ownershipLease = lease;
      await tx.save(found);
      await tx.append(this.evt("manager.ownership_acquired", found, c, { managerInstanceId: c.managerInstanceId }));
      return { status: "succeeded", code: "OWNERSHIP_ACQUIRED", assignment: copy(found) };
    });
  }
}
