export const POLICY_DECISION_CODES = [
  "ALLOW", "APPROVAL_REQUIRED", "APPROVAL_SCOPE_MISMATCH", "APPROVAL_REVISION_MISMATCH",
  "EXECUTION_AUTHORITY_MISSING", "AFFECTED_WORK_HELD", "MATERIAL_CHANGE", "NONMATERIAL_CHANGE",
  "MATERIALITY_AMBIGUOUS", "CUMULATIVE_MATERIALITY_THRESHOLD", "UNKNOWN_OUTCOME_UNRESOLVED",
  "PROVIDER_CAPABILITY_UNAVAILABLE", "MODEL_NOT_ALLOWED", "OWNERSHIP_REQUIRED", "INTENT_PERSISTENCE_EXHAUSTED",
] as const;
export type PolicyDecisionCode = typeof POLICY_DECISION_CODES[number];
export interface PolicyDecision { allowed: boolean; code: PolicyDecisionCode; reason: string }
