import { spawn } from "node:child_process";
import { AgentWorkflowError } from "../../contracts/errors.ts";

export type JiraSecretStorePlatform = "win32" | "linux" | "darwin" | "unsupported";

export interface JiraSecretStore {
  readonly platform: JiraSecretStorePlatform;
  put(reference: string, authorization: string): Promise<void>;
  get(reference: string): Promise<string | undefined>;
  remove(reference: string): Promise<void>;
}

export interface ProcessResult { stdout: string; stderr: string; exitCode: number; }
export type ProcessRunner = (command: string, args: readonly string[], input?: string) => Promise<ProcessResult>;

export const runProcess: ProcessRunner = async (command, args, input) => new Promise((resolve, reject) => {
  const child = spawn(command, [...args], { stdio: ["pipe", "pipe", "pipe"], windowsHide: true });
  let stdout = ""; let stderr = "";
  child.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString("utf8"); });
  child.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString("utf8"); });
  child.once("error", reject);
  child.once("close", (exitCode) => resolve({ stdout, stderr, exitCode: exitCode ?? 1 }));
  child.stdin.end(input);
});

function fail(code: string, message: string, cause?: unknown): never {
  throw new AgentWorkflowError({ code, message, path: "integrations.jira.credentialReference" }, cause === undefined ? undefined : { cause });
}

export function jiraKeychainReference(siteUrl: string): string {
  let host: string;
  try { host = new URL(siteUrl).host.toLowerCase(); } catch { fail("JIRA_SITE_URL_INVALID", "Jira siteUrl must be a valid HTTPS URL."); }
  if (!host) fail("JIRA_SITE_URL_INVALID", "Jira siteUrl must include a host.");
  return `os-keychain:orbitkeep/jira/${host}`;
}

function referenceId(reference: string): string {
  const match = /^os-keychain:orbitkeep\/jira\/([A-Za-z0-9.-]+)$/.exec(reference);
  if (!match?.[1]) fail("JIRA_CREDENTIAL_REFERENCE_INVALID", "Jira credential references must be generated by Orbitkeep setup.");
  return match[1];
}

function powershellScript(action: "put" | "get" | "remove"): string {
  const type = `
using System;
using System.Runtime.InteropServices;
public static class OrbitkeepCred {
 [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] public struct CREDENTIAL { public UInt32 Flags; public UInt32 Type; public string TargetName; public string Comment; public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten; public UInt32 CredentialBlobSize; public IntPtr CredentialBlob; public UInt32 Persist; public UInt32 AttributeCount; public IntPtr Attributes; public string TargetAlias; public string UserName; }
 [DllImport("Advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool CredWrite([In] ref CREDENTIAL credential, UInt32 flags);
 [DllImport("Advapi32.dll", CharSet=CharSet.Unicode, SetLastError=true)] public static extern bool CredRead(string target, UInt32 type, UInt32 flags, out IntPtr credentialPtr);
 [DllImport("Advapi32.dll", SetLastError=true)] public static extern bool CredDelete(string target, UInt32 type, UInt32 flags);
 [DllImport("Advapi32.dll")] public static extern void CredFree(IntPtr buffer);
}`;
  const common = `$target = 'Orbitkeep:Jira:' + [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($args[0])); Add-Type -TypeDefinition @'\n${type}\n'@;`;
  if (action === "put") return `${common} $secret = [Console]::In.ReadToEnd(); $bytes = [Text.Encoding]::UTF8.GetBytes($secret); $pointer = [Marshal]::AllocCoTaskMem($bytes.Length); try { [Marshal]::Copy($bytes, 0, $pointer, $bytes.Length); $credential = New-Object OrbitkeepCred+CREDENTIAL; $credential.Type = 1; $credential.TargetName = $target; $credential.CredentialBlobSize = $bytes.Length; $credential.CredentialBlob = $pointer; $credential.Persist = 2; $credential.UserName = 'orbitkeep'; if (-not [OrbitkeepCred]::CredWrite([ref]$credential, 0)) { throw [ComponentModel.Win32Exception]::new([Marshal]::GetLastWin32Error()) } } finally { [Marshal]::FreeCoTaskMem($pointer) }`;
  if (action === "get") return `${common} $pointer = [IntPtr]::Zero; if (-not [OrbitkeepCred]::CredRead($target, 1, 0, [ref]$pointer)) { exit 3 }; try { $credential = [Marshal]::PtrToStructure($pointer, [type]'OrbitkeepCred+CREDENTIAL'); $bytes = New-Object byte[] $credential.CredentialBlobSize; [Marshal]::Copy($credential.CredentialBlob, $bytes, 0, $bytes.Length); [Console]::Out.Write([Text.Encoding]::UTF8.GetString($bytes)) } finally { [OrbitkeepCred]::CredFree($pointer) }`;
  return `${common} if (-not [OrbitkeepCred]::CredDelete($target, 1, 0)) { if ([Marshal]::GetLastWin32Error() -ne 1168) { throw [ComponentModel.Win32Exception]::new([Marshal]::GetLastWin32Error()) } }`;
}

export class SystemJiraSecretStore implements JiraSecretStore {
  readonly platform: JiraSecretStorePlatform;
  readonly #run: ProcessRunner;
  constructor(options: { platform?: NodeJS.Platform; run?: ProcessRunner } = {}) {
    const detected = options.platform ?? process.platform;
    this.platform = detected === "win32" || detected === "linux" || detected === "darwin" ? detected : "unsupported";
    this.#run = options.run ?? runProcess;
  }

  async put(reference: string, authorization: string): Promise<void> {
    const id = referenceId(reference);
    if (authorization.trim().length === 0) fail("JIRA_CREDENTIAL_UNAVAILABLE", "A Jira authorization value is required.");
    if (this.platform === "win32") { await this.windows("put", id, authorization); return; }
    if (this.platform === "linux") { await this.linux("put", id, authorization); return; }
    fail("JIRA_SECRET_STORE_UNAVAILABLE", "This platform does not provide a supported secure credential store. Use an env: credential reference until a supported store is available.");
  }

  async get(reference: string): Promise<string | undefined> {
    const id = referenceId(reference);
    if (this.platform === "win32") return this.windows("get", id);
    if (this.platform === "linux") return this.linux("get", id);
    fail("JIRA_SECRET_STORE_UNAVAILABLE", "This platform does not provide a supported secure credential store. Use an env: credential reference until a supported store is available.");
  }

  async remove(reference: string): Promise<void> {
    const id = referenceId(reference);
    if (this.platform === "win32") { await this.windows("remove", id); return; }
    if (this.platform === "linux") { await this.linux("remove", id); return; }
  }

  async windows(action: "put" | "get" | "remove", id: string, value?: string): Promise<string | undefined> {
    const encoded = Buffer.from(id, "utf8").toString("base64");
    const result = await this.#run("powershell.exe", ["-NoLogo", "-NoProfile", "-NonInteractive", "-Command", powershellScript(action), encoded], value);
    if (action === "get" && result.exitCode === 3) return undefined;
    if (result.exitCode !== 0) fail("JIRA_SECRET_STORE_UNAVAILABLE", "Windows Credential Manager could not complete the Jira credential operation.");
    return action === "get" ? result.stdout : undefined;
  }

  async linux(action: "put" | "get" | "remove", id: string, value?: string): Promise<string | undefined> {
    const attributes = ["orbitkeep-service", "orbitkeep", "jira-reference", id];
    const args = action === "put" ? ["store", "--label=Orbitkeep Jira", ...attributes] : action === "get" ? ["lookup", ...attributes] : ["clear", ...attributes];
    const result = await this.#run("secret-tool", args, action === "put" ? value : undefined).catch((cause: unknown) => fail("JIRA_SECRET_STORE_UNAVAILABLE", "Linux Secret Service is unavailable. Install and unlock a Secret Service provider, or use an env: credential reference.", cause));
    if (action === "get" && result.exitCode !== 0) return undefined;
    if (result.exitCode !== 0) fail("JIRA_SECRET_STORE_UNAVAILABLE", "Linux Secret Service could not complete the Jira credential operation.");
    return action === "get" ? result.stdout.trimEnd() : undefined;
  }
}
